"""This file has all the functions needed to save the acquired images and to edit the image headers"""

import os
from datetime import datetime, timezone
from pathlib import Path

import astropy.io.fits as fits
import numpy as np


def rotate_image(
    img_data: np.ndarray,
    invert_x: bool = False,
    invert_y: bool = False,
    nrot90deg: int = 0,
) -> np.ndarray:
    """Tool to fix image orientation of an image array.

    Parameters
    ----------
    img_data : numpy.ndarray (n x m)
        numpy array containing a 2D input image array
    invert_x : bool
        flip image array in the x (horizontal) direction
    invert_y : bool
        flip image array in the y (vertical) direction
    nrot90deg : int
        int to define the number of times image array is rotated by 90 deg counterclockwise

    Returns
    -------
    img_data : numpy.ndarray (n x m)
        numpy array containing the output 2D image array
    """
    if invert_x:
        img_data = np.fliplr(img_data)
    if invert_y:
        img_data = np.flipud(img_data)
    if nrot90deg != 0:
        img_data = np.rot90(img_data, k=nrot90deg)

    return img_data


def format_string(string: str) -> str:
    string = str(string)[2:-1]
    return string


def fix_image_orientation(channel: int, em_mode: str, data: np.ndarray) -> np.ndarray:
    setup: dict = {
        "Conventional": {
            1: [False, True, 2],
            2: [False, False, 0],
            3: [True, False, -1],
            4: [False, False, -1],
        },
        "Electron Multiplying": {
            1: [True, True, 2],
            2: [True, False, 0],
            3: [False, False, -1],
            4: [True, False, -1],
        },
    }
    invert_x, invert_y, nrot = setup[em_mode][channel]
    return rotate_image(data, invert_x, invert_y, nrot)


def verify_file_already_exists(file: Path) -> Path:
    if file.is_file:
        now = datetime.now(timezone.utc)
        date_time = now.strftime("%Y%m%dT%H%M%S%f")
        image_name = file.name.split("_")
        img_index = image_name.pop()
        new_file = ""
        for value in image_name:
            new_file += value + "_"
        new_file += f"{date_time[:-4]}" + "_" + img_index
    return Path(file)


def write_error_log(message: str, log_file: str) -> None:
    with open(log_file, "a") as file:
        now = str(datetime.now())
        file.write(now + " - " + message + "\n")


def fix_standard_keywords(hdu: fits.PrimaryHDU) -> fits.PrimaryHDU:
    hdu.header["BZERO"] = (32768, "Zero point in scaling equation")
    hdu.header["BSCALE"] = (1, "Linear factor in scaling equation")
    hdu.header["NAXIS1"] = (hdu.header["NAXIS1"], "Number of columns")
    hdu.header["NAXIS2"] = (hdu.header["NAXIS2"], "Number of rows")
    hdu.header["DATEFILE"] = datetime.now().isoformat()
    hdu.add_datasum(when="Data unit checksum")
    hdu.add_checksum(when="HDU checksum", override_datasum=True)
    return hdu


# --------------------------------------------------------------------------------------------------------------------------

SUB_SYSTEMS = [
    "CCD",
    "GUI",
    "ICS",
    "TCS",
    "FOCUSER",
    "WSTATION",
    "GENERAL KW",
]

# --------------------------------------------------------------------------------------------------------------------------


tcs_json = {
    "broker": "TCSPD160",
    "version": "20240131",
    "cmd": "",
    "objectName": "NO_OBJ",
    "raAcquis": "02:25:32,1",
    "decAcquis": "+03:22:12,1",
    "epochAcquis": "2000.0",
    "airMass": "1.000",
    "julianDate": "2460368.05207",
    "sideralTime": "20:40:07",
    "hourAngle": "00:00:00",
    "date": "27/02/24",
    "time": "10:14:59",
    "rightAscention": "20 40 07",
    "declination": "-22 35 28",
    "wsDefault": "OFF",
    "guideStr": "27/02/24 20:40:07 20 40 07 -22 35 28",
    "guideAng": "   0.00",
    "guideNor": "  97.00",
    "guideEsp": "S",
    "guideCas": "N",
    "guidePlaca": "0.091",
    "statShutter": "",
    "posCup": "",
    "raOnTarget": True,
    "decOnTarget": True,
    "dome": False,
    "domeOnTarget": True,
    "guider": False,
    "mount": False,
    "grossMovement": False,
    "fineMovement": False,
    "objCentrado": False,
    "varTracking": False,
    "shutter": False,
}

focuser_json = {
    "absolute": True,
    "alarm": 0,
    "broker": "Focuser160",
    "cmd": "",
    "connected": True,
    "controller": "Focuser160",
    "device": "2ndMirror",
    "error": "",
    "homing": False,
    "initialized": True,
    "isMoving": False,
    "maxSpeed": 500,
    "maxStep": 50700,
    "position": 32100,
    "tempComp": False,
    "tempCompAvailable": False,
    "temperature": 0,
    "timestamp": "2024-02-27T10:15:48.255",
    "version": "1.0.0",
}

WS_json = {
    "broker": "Weather160",
    "version": "1.0.0",
    "date": "19/11/25",
    "hour": "15:15",
    "outTemp": "15.8",
    "hiTemp": "15.9",
    "lowTemp": "15.8",
    "outHumidity": "72",
    "dewOut": "10.8",
    "windSpeed": "11.3",
    "windDirection": "ENE",
    "windRun": "0.19",
    "hiSpeed": "19.3",
    "hiDir": "ENE",
    "windChill": "15.4",
    "heatIndex": "15.5",
    "THWIndex": "15.1",
    "THSWIndex": "---",
    "pressure": "755.6",
    "rain": "0.00",
    "rainRate": "0.0",
    "solarRad": "679",
    "solarEnergy": "0.97",
    "hiSolarRad": "679",
    "UVIndex": "3.8",
    "UVDose": "0.03",
    "hiUV": "3.8",
    "headDD": "0.002",
    "coolDD": "0.000",
    "inTemp": "18.8",
    "inHumidity": "63",
    "dewIn": "11.6",
    "inHeat": "18.4",
    "inEMC": "11.63",
    "inAirDensity": "1.1865",
    "2ndTemp": "20.0",
    "2ndHumidity": "50",
    "ET": "0.00",
    "leaf": "0",
    "windSamp": "22",
    "windTx": "1",
    "ISSRecept": "95.7",
    "arcInt": "1",
}

s4gui_json = {
    "OBJECT": "Test",
    "OBSERVER": "Denis",
    "CTRLINTE": "S4GEI",
    "PROJID": "ENG",
    "SYNCMODE": "ASYNC",
    "INSTMODE": "PHOT",
    "FILTER": "CLEAR",
    "OBSTYPE": "OBJECT",
    "GUIVRSN": "v0.0.0",
    "COMMENT": "",
    "broker": "S4GEI",
    "timestamp": "0000-00-00T00:00:00.0",
    "CHANNEL 1": True,
    "CHANNEL 2": False,
    "CHANNEL 3": False,
    "CHANNEL 4": False,
    "TCSMODE": True,
}

general_kw = {
    "ACSVRSN": "v1.56.0",
    "ACSMODE": False,
    "filename": "20251223_s4c1_20251221.fits",
    "ncycles": 1,
    "cyclind": 0,
    "channel": 1,
    "ACQERROR": False,
    "seqindex": 0,
    "nseq": 1,
}
ccd_kw = {
    "FILENAME": "20251223_s4c1_20251221.fits",
    "FRAMEIND": 0,
    "CCDTEMP": 0,
    "TEMPST": "TEMPERATURE_OFF",
    "CCDSERN": 9914,
    "PREAMP": 0,
    "READRATE": 0,
    "VSHIFT": 3,
    "VCLKAMP": 0,
    "ACQMODE": 3,
    "SHUTTER": 2,
    "TRIGGER": 0,
    "VBIN": 1,
    "INITLIN": 1,
    "INITCOL": 1,
    "FINALLIN": 1024,
    "FINALCOL": 1024,
    "HBIN": 1,
    "EXPTIME": 1.5,
    "NFRAMES": 1,
    "COOLER": 0,
    "TGTEMP": 0,
    "date-obs": "2025-12-23T18:35:10.271484",
    "utdate": "2025-12-23",
    "uttime": "18:35:10.271484",
    "EMGAIN": 2,
    "FRAMETRF": True,
    "EMMODE": 1,
}
ics_kw = {
    "broker": "S4ICS",
    "version": "v0.0.0",
    "comment": "this is a comment",
    "tcpServerSocket": "192.168.1.170",
    "tcpServerEnabled": "True",
    "timestamp": "0000-00-00T00:0:000.0",
    "mechanisms": [
        {
            "name": "WPROT",
            "status": {
                "mode": "ACTIVE",
                "condition": "READY",
                "position": "0",
                "pos_name": "HOME",
                "pos_id": "-1",
            },
        },
        {
            "name": "WPSEL",
            "status": {
                "mode": "ACTIVE",
                "condition": "BUSY",
                "position": "50",
                "pos_name": "OFF",
                "pos_id": "2",
            },
        },
        {
            "name": "CALW",
            "status": {
                "mode": "ACTIVE",
                "condition": "TIMEOUT",
                "position": "144",
                "pos_name": "OFF",
                "pos_id": "3",
            },
        },
        {
            "name": "ASEL",
            "status": {
                "mode": "ACTIVE",
                "condition": "NONE",
                "position": "0",
                "pos_name": "OFF",
                "pos_id": "1",
            },
        },
        {
            "name": "GMIR",
            "status": {
                "mode": "ACTIVE",
                "condition": "READY",
                "position": "0",
                "pos_name": "HOME",
                "pos_id": "0",
            },
        },
        {
            "name": "GFOC",
            "status": {
                "mode": "ACTIVE",
                "condition": "READY",
                "position": "0",
                "pos_name": "HOME",
                "pos_id": "0",
            },
        },
    ],
}

everthing_json = {
    "CYCLIND": 0,
    "FILENAME": "20240515_s4c1_000008_test1.fits",
    "FRAMEIND": 1,
    "CCDTEMP": -60,
    "TEMPST": "TEMPERATURE_STABILIZED",
    "CCDSERN": 9914,
    "SEQINDEX": 0,
    "WPPOS": 0,
    "PREAMP": 0,
    "READRATE": 0,
    "EMGAIN": 2,
    "VSHIFT": 3,
    "FRAMETRF": True,
    "VCLKAMP": 0,
    "ACQMODE": 3,
    "EMMODE": 1,
    "SHUTTER": 2,
    "TRIGGER": 0,
    "VBIN": 1,
    "INITLIN": 1,
    "INITCOL": 1,
    "FINALLIN": 1024,
    "FINALCOL": 1024,
    "HBIN": 1,
    "EXPTIME": 1.2000000476837158203,
    "NFRAMES": 1,
    "NCYCLES": 1,
    "NSEQ": 1,
    "TGTEMP": -60,
    "COOLER": 1,
    "ACSVRSN": "v1.46.14",
    "CHANNEL": 1,
    "ACSMODE": True,
    "OBSERVER": "",
    "OBJECT": "",
    "CTRLINTE": "S4GUI",
    "PROJID": "",
    "SYNCMODE": "ASYNC",
    "INSTMODE": "PHOT",
    "FILTER": "CLEAR",
    "OBSTYPE": "OBJECT",
    "CHANNEL 1": True,
    "CHANNEL 2": False,
    "CHANNEL 3": False,
    "CHANNEL 4": False,
    "TCSMODE": True,
    "COMMENT": "",
    "BROKER": "S4GUI",
    "GUIVRSN": "v. 2024.05.15",
    "WPROT": "NONE",
    "WPROT_MODE": "ACTIVE",
    "WPSEL": "OFF",
    "WPSEL_MODE": "NONE",
    "CALW": "OFF",
    "CALW_MODE": "ACTIVE",
    "ASEL": "OFF",
    "ASEL_MODE": "ACTIVE",
    "GMIR": "0.000",
    "GMIR_MODE": "ACTIVE",
    "GFOC": "0.000",
    "GFOC_MODE": "ACTIVE",
    "broker": "TCSPD160",
    "version": "20240131",
    "cmd": "",
    "objectName": "               ",
    "raAcquis": "        ",
    "decAcquis": "        ",
    "epochAcquis": "",
    "airMass": "1.001",
    "julianDate": "2460446.24348",
    "sideralTime": "06:24:02",
    "hourAngle": "00:00:00",
    "date": "15/05/24",
    "time": "14:50:37",
    "rightAscention": "06 24 02",
    "declination": "-24 50 43",
    "wsDefault": "OFF",
    "guideStr": "15/05/24 06:24:02 06 24 02 -24 50 43",
    "guideAng": "   0.10",
    "guideNor": " 180.00",
    "guideEsp": "S",
    "guideCas": "S",
    "guidePlaca": "0.200",
    "statShutter": "",
    "posCup": "",
    "raOnTarget": False,
    "decOnTarget": False,
    "dome": False,
    "domeOnTarget": False,
    "guider": False,
    "mount": False,
    "grossMovement": False,
    "fineMovement": False,
    "objCentrado": False,
    "varTracking": False,
    "shutter": False,
    "absolute": True,
    "alarm": 0,
    "broker": "Focuser160",
    "cmd": {"clientId": 0, "clientTransactionId": 0, "clientName": "", "action": ""},
    "connected": True,
    "controller": "Focuser160",
    "device": "2ndMirror",
    "error": "",
    "homing": False,
    "initialized": False,
    "isMoving": False,
    "maxSpeed": 500,
    "maxStep": 50700,
    "position": 0,
    "tempComp": False,
    "tempCompAvailable": False,
    "temperature": 0,
    "timestamp": "2024-05-15T14:50:48.242",
    "version": "1.0.0",
    "broker": "Weather160",
    "version": "1.0.0",
    "date": "15/05/24",
    "hour": "14:45",
    "outTemp": "17.2",
    "hiTemp": "17.5",
    "lowTemp": "17.2",
    "outHumidity": "85",
    "dewOut": "14.6",
    "windSpeed": "6.4",
    "windDirection": "WSW",
    "windRun": "0.54",
    "hiSpeed": "14.5",
    "hiDir": "W",
    "windChill": "17.2",
    "heatIndex": "17.4",
    "THWIndex": "17.4",
    "THSWIndex": "---",
    "pressure": "758.1",
    "rain": "0.00",
    "rainRate": "0.0",
    "solarRad": "298",
    "solarEnergy": "2.14",
    "hiSolarRad": "355",
    "UVIndex": "1.8",
    "UVDose": "0.06",
    "hiUV": "1.8",
    "headDD": "0.004",
    "coolDD": "0.000",
    "inTemp": "22.1",
    "inHumidity": "62",
    "dewIn": "14.5",
    "inHeat": "22.1",
    "inEMC": "11.31",
    "inAirDensity": "1.1737",
    "2ndTemp": "---",
    "2ndHumidity": "---",
    "ET": "0.00",
    "leaf": "0",
    "windSamp": "115",
    "windTx": "1",
    "ISSRecept": "100.0",
    "arcInt": "5",
    "DATE-OBS": "2024-05-15T17:50:37.609000",
    "UTTIME": "17:50:37.609000",
    "UTDATE": "2024-05-15",
}

test_json = {
    "CYCLIND": 0,
    "FILENAME": "20240528_s4c1_000005.fits",
    "FRAMEIND": 1,
    "CCDTEMP": 20,
    "TEMPST": "TEMPERATURE_OFF",
    "CCDSERN": 9914,
    "SEQINDEX": 0,
    "WPPOS": 0,
    "PREAMP": 0,
    "READRATE": 0,
    "EMGAIN": 2,
    "VSHIFT": 3,
    "FRAMETRF": True,
    "VCLKAMP": 0,
    "ACQMODE": 3,
    "EMMODE": 1,
    "SHUTTER": 2,
    "TRIGGER": 0,
    "VBIN": 1,
    "INITLIN": 1,
    "INITCOL": 1,
    "FINALLIN": 1024,
    "FINALCOL": 1024,
    "HBIN": 1,
    "EXPTIME": 1.5,
    "NFRAMES": 1,
    "NCYCLES": 1,
    "NSEQ": 1,
    "TGTEMP": 20,
    "COOLER": 0,
    "ACSVRSN": "v1.47.2",
    "CHANNEL": 1,
    "ACSMODE": False,
    "broker": "TCSPD160",
    "version": "20240131",
    "cmd": "",
    "objectName": "HR0591         ",
    "raAcquis": "01:58:46",
    "decAcquis": "-61:34:11",
    "epochAcquis": "2000.0",
    "airMass": "1.000",
    "julianDate": "2460460.07144",
    "sideralTime": "03:10:50",
    "hourAngle": "-0:00:00",
    "date": "29/05/24",
    "time": "10:42:53",
    "rightAscention": "03 10 50",
    "declination": "-22 32 03",
    "wsDefault": "OFF",
    "guideStr": "29/05/24 03:10:50 03 10 50 -22 32 03",
    "guideAng": "   0.10",
    "guideNor": " 180.00",
    "guideEsp": "S",
    "guideCas": "S",
    "guidePlaca": "0.200",
    "statShutter": "",
    "posCup": "",
    "raOnTarget": True,
    "decOnTarget": True,
    "dome": False,
    "domeOnTarget": True,
    "guider": False,
    "mount": False,
    "grossMovement": False,
    "fineMovement": False,
    "objCentrado": False,
    "varTracking": False,
    "shutter": False,
    "absolute": True,
    "alarm": 0,
    "broker": "Focuser160",
    "cmd": {"clientId": 0, "clientTransactionId": 0, "clientName": "", "action": ""},
    "connected": True,
    "controller": "Focuser160",
    "device": "2ndMirror",
    "error": "",
    "homing": False,
    "initialized": True,
    "isMoving": False,
    "maxSpeed": 500,
    "maxStep": 50700,
    "position": 34500,
    "tempComp": False,
    "tempCompAvailable": False,
    "temperature": 0,
    "timestamp": "2024-05-29T10:43:00.242",
    "version": "1.0.0",
    "broker": "Weather160",
    "version": "1.0.0",
    "date": "29/05/24",
    "hour": "10:40",
    "outTemp": "11.4",
    "hiTemp": "11.4",
    "lowTemp": "11.3",
    "outHumidity": "92",
    "dewOut": "10.2",
    "windSpeed": "12.9",
    "windDirection": "W",
    "windRun": "1.07",
    "hiSpeed": "20.9",
    "hiDir": "W",
    "windChill": "9.8",
    "heatIndex": "11.6",
    "THWIndex": "9.9",
    "THSWIndex": "---",
    "pressure": "762.9",
    "rain": "0.00",
    "rainRate": "0.0",
    "solarRad": "636",
    "solarEnergy": "4.56",
    "hiSolarRad": "657",
    "UVIndex": "3.7",
    "UVDose": "0.13",
    "hiUV": "3.9",
    "headDD": "0.024",
    "coolDD": "0.000",
    "inTemp": "17.7",
    "inHumidity": "65",
    "dewIn": "11.1",
    "inHeat": "17.3",
    "inEMC": "11.97",
    "inAirDensity": "1.2030",
    "2ndTemp": "---",
    "2ndHumidity": "---",
    "ET": "0.00",
    "leaf": "0",
    "windSamp": "114",
    "windTx": "1",
    "ISSRecept": "100.0",
    "arcInt": "5",
    "DATE-OBS": "2024-05-29T13:42:54.334162",
    "UTTIME": "13:42:54.334162",
    "UTDATE": "2024-05-29",
}
